language: node_js
node_js: "node"
os: "linux"
dist: "xenial"
jobs:
  include:
    - stage: "ESLint"
      script: npm run lint
    - stage: "Test"
      script: npm test
    - stage: "Coverage"
      if: branch = main
      before_script:
        - bash <(curl -Ls https://coverage.codacy.com/get.sh) download
      script: npm run coverage
      after_success:
        - bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r coverage/lcov.info
